version: "3.5"
volumes:
  data:
services:
  database:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=postgres
      - POSTGRES_DB=check_in_app
    volumes:
      - data:/var/lib/postgres/data
