name: Run E2E Tests

on: [pull_request]

jobs:
  run-e2e-tests:
    name: Run E2E Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        ports:
          - 5432:5432
        env:
          POSTGRESQL_USERNAME: pgdocker
          POSTGRESQL_PASSWORD: pgdocker
          POSTGRESQL_DATABASE: check_in_app

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - run: npm ci

      - run: npm run test:e2e
        env:
          JWT_SECRET: testing_secret
          DATABASE_URL: "postgresql://pgdocker:pgdocker@localhost:5432/check_in_app?schema=public"